### ISSUE TITLE
Kotlin extensions for Reactor

### ISSUE THREAD

**Issue by dynaxis** [KotlinBy/awesome-kotlin#123]
https://github.com/reactor/reactor-kotlin-extensions/

It's like RxKotlin for RxJava, but for Reactor.

**Comment by dynaxis** [comment]
First of all, thank you for taking time to add this entry. Though this issue is resolved and closed, I have a quick question.

`reactor-kotlin-extensions` is named "extensions," but it's comparable to `RxKotlin`, even if it refers to itself as a `RxJava` binding. The two are similar even in how they are implemented. As `RxJava` and `Reactor-core` are comparable, I think placing `RxKotlin` and `reactor-kotlin-extensions` in different categories may confuse visitors.

Any opinion? IMHO, it would be more appropriate to put RxKotlin` and `reactor-kotlin-extensions` under the same category. Move the latter into the functional programming section?

**Comment by IRus** [comment]
@dynaxis Yep, you right, this projects (as well as many others) not perfectly categorized. It's like `RxKotlin` and  `reactor-kotlin-extensions` can be part of fp section, as well as part of extensions section. I will move `reactor-kotlin-extensions` to fp section.
