### ISSUE TITLE
A call to ARMS :)

### ISSUE THREAD

**Issue by dpapathanasiou** [KotlinBy/awesome-kotlin#172]
```
name = "dpapathanasiou/ARMS"
desc = "Another RESTful Mongo Service"
href = "https://github.com/dpapathanasiou/ARMS"
tags = Tags["database", "mongo", "mongodb", "CRUD", "read", "write", "update", "delete", "query", "web", "http", "rest"]
```

**Comment by dpapathanasiou** [comment]
Before I saw this, I was a bit confused about the [contribution process](https://github.com/KotlinBy/awesome-kotlin/blob/master/CONTRIBUTING.md): I cloned the repo, created a new branch, edited [links/Libraries.kts](https://github.com/KotlinBy/awesome-kotlin/blob/master/links/Libraries.kts) in the Database subcategory, but I was denied trying to push the branch and create a pull request.

**Comment by McPringle** [comment]
To create a pull request, you need to *fork* the repository and push your changes to your *fork*. Then you can create a pull request from your *fork* to the *upstream* repository.

**Comment by dpapathanasiou** [comment]
@McPringle I know, right? Why don't people follow the correct procedures? 

![381a7e31652a7ccf16b390d7823bb5625d1844ab9e05dc1168d6cdc9b8e22eee](https://user-images.githubusercontent.com/1387395/42508011-14f85100-8415-11e8-9401-abc7db085637.jpg)

Seriously, though, that's overkill for a simple entry like this.

If you guys want to add it, great; if not, it's no sweat either.

**Comment by McPringle** [comment]
@dpapathanasiou That is how **git** and **GitHub** works and has nothing to do with this project. It is the same for **all** projects on GitHub.

**Comment by dpapathanasiou** [comment]
@McPringle you are doing God's work! Dankeschön!
