### ISSUE TITLE
Add Buffer MVI clean architecture boilerplate

### ISSUE THREAD

**Issue by hitherejoe** [KotlinBy/awesome-kotlin#261]
name = "Android Clean Architecture Model-View-Intent Boilerplate"
desc = "A clean architecture boilerplate using android written in Kotlin and using the Model-View-Intent pattern"
href = "https://github.com/bufferapp/android-clean-architecture-mvi-boilerplate"
tags = Tags["cleanarchitecture", "android", "boilerplate", "mvi"]

**Comment by madhead** [comment]
Hey, @hitherejoe, do you still support it? The repo seems to be abandoned.
