### ISSUE TITLE
Add RxTest

### ISSUE THREAD

**Issue by RubyLichtenstein** [KotlinBy/awesome-kotlin#262]
```
name = "RubyLichtenstein/RxTest"
desc = "Kotlin DSL for testing RxJava2"
href = "https://github.com/RubyLichtenstein/RxTest"
tags = Tags["rxjava2", "kotlin",  "kotlin-android",  "testing", "kotlin-dsl"]
```

**Comment by madhead** [comment]
Hey, @RubyLichtenstein, is your library still actual? I don't see any recent commits, confused a little bit…

**Comment by IRus** [comment]
@madhead with https://github.com/KotlinBy/awesome-kotlin/issues/104 it's ok to add even non actual libraries, since we will filter them from main page
