### ISSUE TITLE
Remove KotterKnife?

### ISSUE THREAD

**Issue by jt-gilkeson** [KotlinBy/awesome-kotlin#360]
I could be wrong, but it seems like kotlin-android-extensions makes it obsolete?

**Comment by Sylk** [comment]
Update on this?

**Comment by IRus** [comment]
Archived github repo appears with opacity, and removed from readme.
![image](https://user-images.githubusercontent.com/493656/77511825-ee3cfe80-6e82-11ea-9cfc-f62142a00573.png)
