### ISSUE TITLE
List of Syntax Highlighters for Kotlin

### ISSUE THREAD

**Issue by hastebrot** [KotlinBy/awesome-kotlin#38]
Here's an initial, uncomplete list with the current status.

- **Rouge** (Ruby, incomplete): https://github.com/jneen/rouge/pull/354
- **highlight.js** (JavaScript, out-of-date): https://github.com/isagalaev/highlight.js/blob/master/src/languages/kotlin.js
- **Pygments** (Python, complete): https://bitbucket.org/birkenfeld/pygments-main/src/ef81d4814b/pygments/lexers/jvm.py
- **Linguist** (Ruby/Github, uses Sublime package): https://github.com/github/linguist/search?q=kotlin

**Comment by IRus** [comment]
Thank you! I added this projects in list. #39
