### ISSUE TITLE
 AwesomeKotlin IntelliJ Plugin published

### ISSUE THREAD

**Issue by roger-yh99** [KotlinBy/awesome-kotlin#387]
Please checkout 
https://plugins.jetbrains.com/plugin/11357-awesome-kotlin

- Show content from Awesome Kotlin inside IDE ToolWindow
- Search / checkout projects from GitHub repo
- Custom content sources & dynamic KotlinScript loading is supported

**Comment by IRus** [comment]
I believe this can be closed per: https://github.com/KotlinBy/awesome-kotlin/pull/385
