### ISSUE TITLE
Add Coiny - Cryptocurrency App

### ISSUE THREAD

**Issue by pranayairan** [KotlinBy/awesome-kotlin#403]
If you want submit new link, please fill this:

```
name = "CoinBit"
desc = "CoinBit is completely free Bitcoin & cryptocurrency portfolio tracker app. It helps you over 4000+ cryptocurrencies on 150+ platforms including Binance, GDAX, Kraken etc"
href = "https://github.com/pranayairan/CoinBit"
tags = Tags["cryptocurrency,kotlin,android,app"]
```

**Comment by madhead** [comment]
Hey, @pranayairan! Although I see your app in the Play Market, the source is not available anymore, isn't it?

**Comment by IRus** [comment]
Maybe it's https://github.com/pranayairan/CoinBit ?

**Comment by madhead** [comment]
Their packages differ in Play Market, but, yeah, this one seems to be the one that should be featured…

**Comment by pranayairan** [comment]
Hi MadHead, thanks yes https://github.com/pranayairan/CoinBit is the correct one. I have to rename the app and package due to some conflicts.
