### ISSUE TITLE
Can't access IP from some areas

### ISSUE THREAD

**Issue by voddan** [KotlinBy/awesome-kotlin#409]
I was unable to access kotlin.link from Russia lately. 

Couple months back it all worked. With VPN to USA it also worked. 

I checked Russian's censorship site https://eais.rkn.gov.ru/, but `138.68.123.234` is not on the blocked list.

Please investigate the situation and/or add another IP for this amazing site!

**Comment by IRus** [comment]
Can you `mtr kotlin.link` next time?

**Comment by IRus** [comment]
No more reports about this issue, so I'll close it.
