### ISSUE TITLE
Mark khttp as deprecated

### ISSUE THREAD

**Issue by debuglevel** [KotlinBy/awesome-kotlin#419]
Unfortunately, https://github.com/jkcclemens/khttp seems no longer be maintained. :-(

Although it is still an really awesome library, a "curated awesome list" should IMHO not promote libraries which did not get any updates for 3 years.

**Comment by IRus** [comment]
Automated check implemented in order to hide such libraries: https://github.com/KotlinBy/awesome-kotlin/blob/main/src/main/kotlin/link/kotlin/scripts/LinksProcessor.kt#L155
