### ISSUE TITLE
Remove Injekt?

### ISSUE THREAD

**Issue by dynaxis** [KotlinBy/awesome-kotlin#44]
According to [this](https://github.com/kohesive/injekt/blob/master/README.md#notice--kodein-and-injekt-much-of-the-same), Injekt is giving its way to Kodein in preference to having only one library doing the same registry based DI.

Injekt people don't seem to recommend use of Injekt for new projects, so it may be good to remove Injekt from the list to avoid any future confusion.

**Comment by IRus** [comment]
Thank you for notice! 

I will delete Injekt in future, but for now Injekt still nice example of Kotlin's power for implementing DIs.

**Comment by dynaxis** [comment]
Agreed. Then it would be good if there is some notice that Kodein is recommended.

**Comment by IRus** [comment]
See commit c04c7bd
