### ISSUE TITLE
articles/.links folder contains some files with : in their filenames

### ISSUE THREAD

**Issue by cybernetics** [KotlinBy/awesome-kotlin#447]
articles/.links folder contains some files with a colon in their filenames. a colon is not allowed as part of a filename in windows OS. due to this, cloning this repo in localhost creates files with incomplete filenames.

![image](https://user-images.githubusercontent.com/79887/56679505-107a3b00-667a-11e9-962a-5452568d0c7a.png)

![image](https://user-images.githubusercontent.com/79887/56679527-1c65fd00-667a-11e9-8a81-3896d64d9613.png)

![image](https://user-images.githubusercontent.com/79887/56679563-37387180-667a-11e9-88f4-0be2ad12814f.png)

**Comment by IRus** [comment]
@cybernetics Thanks for reporting, I'll look into that
