### ISSUE TITLE
kotlin.link badage response 404 now. 

### ISSUE THREAD

**Issue by vincentlauvlwj** [KotlinBy/awesome-kotlin#590]
https://kotlin.link/awesome-kotlin.svg

**Comment by IRus** [comment]
Nice catch @vincentlauvlwj !
I [moved](https://github.com/KotlinBy/awesome-kotlin/commit/971a9bc159abce4ca174b9221cfcf23bde2d7850#diff-60254338249f657a0a83f98258a56bfeL10) generation phase to build from deploy to catch errors in kts early, and forgot to delete rm statement.
