### ISSUE TITLE
Github Links are Broken

### ISSUE THREAD

**Issue by sgarfinkel** [KotlinBy/awesome-kotlin#591]
I hope this wasn't done maliciously.

All `https://github.com` links were changed to `https://githib.com` in the most recent commit (3a6045d34e0d9cbe14db0213fe44a335e277dd28).

This is caused by a typo here: https://github.com/KotlinBy/awesome-kotlin/blob/1c0a60b66f2235b85a329617b004b075ea1e0d2e/src/main/kotlin/link/kotlin/scripts/LinksProcessor.kt#L42

**Comment by IRus** [comment]
Much thanks!
