### ISSUE TITLE
The header is "jumping" when cycling through the logos

### ISSUE THREAD

**Issue by madhead** [KotlinBy/awesome-kotlin#603]
When I cycle through the logos by clicking them the header is changing its height and the page content is jumping:

![image](https://user-images.githubusercontent.com/577360/94975259-cb6a6180-0519-11eb-9fa0-4af93a745daf.png)

**Comment by IRus** [comment]
It's shouldn't happens, cause right now header is banner. How you able to cycle through the logos?

<img width="1780" alt="image" src="https://user-images.githubusercontent.com/493656/94976002-2c933480-051c-11eb-825c-e78b121d7426.png">

**Comment by madhead** [comment]
Well, I changed to `show: () => false` in `head.tsx` :)

Yeah, these days it's a banner, but when the event is over, I guess this particular logo will be turned off, won't it?

**Comment by IRus** [comment]
Currently I manually edit CSS to switch between banner/logo mode. Of cause better way to fix is switch to separate banner component and separate logos component. And switch between them
