### ISSUE TITLE
Wasted vertical space in links 

### ISSUE THREAD

**Issue by madhead** [KotlinBy/awesome-kotlin#605]
Right now, the links are rendered in the order they are declared in `awesome.kts` files. Is it intentional or not?

If not, I see an issue. If a section with a few (like one) links follows a section with a lot of links, the vertical space is wasted. See how effective it is used in "Coroutines" / "Functional Programming" / "JSON" (almost no vertical space is lost because all the section are ± the same number of links) and how it is wasted in the CI section, who is a neighbor to the "Database" section with a dozen of links. 

![image](https://user-images.githubusercontent.com/577360/94975975-138a8380-051c-11eb-899e-68886bc9f79e.png)

I think we can solve it if needed bu just sorting the sections by the number of links.

**Comment by IRus** [comment]
I believe vertical alignment was intentional. Without wasting vertical space navigation becomes harder (cause user have to scan horizontally and vertically at the same time). Maybe we can group subcategories by number of links, to waste less vertical space

**Comment by madhead** [comment]
Yes, I mean that. Just group (sort) the sections by the number of links, so that the difference in the number of links in each row is mininal.

**Comment by IRus** [comment]
Agree
