### ISSUE TITLE
KTX: Kotlin utilities for LibGDX games and applications

### ISSUE THREAD

**Issue by czyzby** [KotlinBy/awesome-kotlin#61]
Makes [LibGDX](https://libgdx.badlogicgames.com/) feel like an actual Kotlin game framework.

[GitHub repository.](https://github.com/czyzby/ktx)

**Comment by IRus** [comment]
Close by https://github.com/KotlinBy/awesome-kotlin/commit/add14fde9fd7af8ee32862d454ab4935a59121b7

**Comment by IRus** [comment]
Thank you!

**Comment by czyzby** [comment]
I just noticed that you added KTX to a new `Game development` category, but kept FXGL (an actual game framework based on JavaFX) in `Desktop`. Maybe they should be kept together?

**Comment by IRus** [comment]
@czyzby Yea, i totally agree, just forgot about it.
