### ISSUE TITLE
Add new sqlite ORM library to Database section

### ISSUE THREAD

**Issue by s4kibs4mi** [KotlinBy/awesome-kotlin#62]
PultusORM is a sqlite ORM implementation for kotlin on top of sqlite jdbc driver.
[https://github.com/s4kibs4mi/PultusORM](https://github.com/s4kibs4mi/PultusORM)

**Comment by IRus** [comment]
Closed via https://github.com/KotlinBy/awesome-kotlin/commit/9dc02e5de65872f4fc3226df4f8e42ee375f27cc
Thank you for contribution!

**Comment by s4kibs4mi** [comment]
You are welcome :)
