### ISSUE TITLE
Please move detekt from misc to tools section

### ISSUE THREAD

**Issue by arturbosch** [KotlinBy/awesome-kotlin#80]
As this will give more attention to the tool? I released today milestone 3 with many more rules.

Thx in advance.

**Comment by IRus** [comment]
Yea, i completely agree with you. Moved https://github.com/KotlinBy/awesome-kotlin/commit/9906ae071d80bf3d878eb440a42da740ca6e5715 

And now awesome-kotlin have badge, so if you like, you can add it in readme:
```
[![Awesome Kotlin Badge](https://kotlin.link/awesome-kotlin.svg)](https://github.com/KotlinBy/awesome-kotlin)
```

**Comment by arturbosch** [comment]
I use the badge now thx ;)

**Comment by IRus** [comment]
I appreciate it, thanks :+1:
