### ISSUE TITLE
Suggestion to addition: KAConf Configuration System

### ISSUE THREAD

**Issue by mariomac** [KotlinBy/awesome-kotlin#82]
- [KAConf](https://github.com/mariomac/kaconf) - KickAss Configuration. An annotation-based configuration system for Java and Kotlin

**Comment by IRus** [comment]
Thanks for another contribution!

If you like, you can add awesome-kotlin badge at your README.

```
[![Awesome Kotlin Badge](https://kotlin.link/awesome-kotlin.svg)](https://github.com/KotlinBy/awesome-kotlin)
```

**Comment by mariomac** [comment]
I'll do. Thanks!
