### ISSUE TITLE
KotlinPorts first repo

### ISSUE THREAD

**Issue by ivanpopelyshev** [KotlinBy/awesome-kotlin#92]
Hello!

I converted async db driver from scala: https://github.com/KotlinPorts/kt-postgresql-async

Currently postgres is supported, and only first test is converted. 

I hope to add more repos to that github group soon ;)

**Comment by IRus** [comment]
> I hope to add more repos to that github group soon ;)

I hope so, i don't know how to follow entire organization on github, so i hope you will notice here about new ports! 

Thanks for contribution! :+1:
