### ISSUE TITLE
Brisbane Kotlin Meetup Group

### ISSUE THREAD

**Issue by jamesbassett** [KotlinBy/awesome-kotlin#93]
Hi @IRus, 

I had issues getting npm to work for a PR, so raising this as an issue :)

Could you add the Brisbane (Australia) Kotlin Meetup Group to the website?

`kotlin.ts` changes [here](https://github.com/KotlinBy/awesome-kotlin/compare/master...jamesbassett:brisbane-meetup)

Thanks!

**Comment by IRus** [comment]
> I had issues getting npm to work for a PR, so raising this as an issue :)

I hope very soon i rewrite all this things with Kotlin)

Thanks for contribution!
