### ISSUE TITLE
Krawler a Kotlin native web crawler framework based on Java's crawler4j

### ISSUE THREAD

**Issue by brianmadden** [KotlinBy/awesome-kotlin#97]
http://github.com/brianmadden/krawler - Krawler is a Kotlin native web crawler framework based on Java's crawler4j. 

Thank you :)

**Comment by IRus** [comment]
Hi, i will add this library as soon, as i'm done with first part of "Rewrite \w Kotlin. #89"

**Comment by brianmadden** [comment]
Great, thank you.
:+1:
